blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.ArticleList.as_view(), name='home'),
    path('page/<int:page>', views.ArticleList.as_view(), name='home'),
    path('article/<slug:slug>', views.ArticleDetail.as_view(), name='detail'),
    path('preview/<int:pk>', views.ArticlePreview.as_view(), name='preview'),
    path('category/<slug:slug>', views.CategoryList.as_view(), name='category'),
    path('category/<slug:slug>/page/<int:page>', views.CategoryList.as_view(), name='category'),
    path('author/<slug:usr>', views.AuthorList.as_view(), name='author'),
    path('author/<slug:usr>/page/<int:page>', views.AuthorList.as_view(), name='author'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('account/', include('account.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from account.models import User
from django.utils.html import format_html
from extensions.utils import jalali_converter


# managers
class ArticleManager(models.Manager):
    def published(self):
        return self.filter(status='p')


class CategoryManager(models.Manager):
    def active(self):
        return self.filter(status=True)


# Create your models here.


class Category(models.Model):
    parent = models.ForeignKey('self', default=None, blank=True, null=True, on_delete=models.SET_NULL, related_name='children', verbose_name='زیردسته')
    title = models.CharField(max_length=200, verbose_name='عنوان')
    slug = models.SlugField(max_length=100, unique=True, verbose_name='ادرس')
    status = models.BooleanField(default=True, verbose_name='ایا نمایش داده شود')
    position = models.IntegerField(verbose_name='پوزیشن')

    class Meta:
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی ها'
        ordering = ['parent__id', '-position']

    def __str__(self):
        return self.title

    objects = CategoryManager()


class Article(models.Model):
    STATUS_CHOICE = (
        ('p', 'منتشرشده'),
        ('d', 'پیش تویس'),
        ('i', 'بررسی'),
        ('b', 'برگشت داده شده'),
    )
    author = models.ForeignKey(User, null=True, default=None, blank=True, on_delete=models.SET_NULL, verbose_name='نویسنده', related_name='articles')
    title = models.CharField(max_length=200, verbose_name='عنوان')
    slug = models.SlugField(max_length=100, unique=True, verbose_name='ادرس')
    category = models.ManyToManyField(Category, verbose_name='دسته بندی', related_name='articles')
    description = models.TextField(verbose_name='توضیحات')
    thumbnail = models.ImageField(upload_to='images', verbose_name='تصویر')
    publish = models.DateTimeField(default=timezone.now, verbose_name='تاریخ انتشار')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    is_special = models.BooleanField(default=False, verbose_name='مقاله ویژه')
    status = models.CharField(max_length=1, choices=STATUS_CHOICE, verbose_name='وضعیت')

    def __str__(self):
        return self.title

    def jpublish(self):
        return jalali_converter(self.publish)
    jpublish.short_description = 'تاریخ انتشار'

    class Meta:
        verbose_name = 'مقاله'
        verbose_name_plural = 'مقالات'
        ordering = ['-publish']

    def category_to_str(self):
        return ' ,'.join([category.title for category in self.category_published()])
    category_to_str.short_description = 'دسته بندی'

    def category_published(self):
        return self.category.filter(status=True)

    def thumbnail_tag(self):
        return format_html(f'<img width=80 src="{self.thumbnail.url}"/>')
    thumbnail_tag.short_description = 'تصویر'

    objects = ArticleManager()

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.views.generic import ListView, DetailView
# from django.http import HttpResponse
from . import models
from account.mixins import ArticleAccessMixin
from account.models import User
# Create your views here.


"""
def home(request, page=1):
    paginator = Paginator(models.Article.objects.published(), 4)
    articles = paginator.get_page(page)
    context = {
        'articles': articles
    }
    return render(request, 'blog/article_list.html', context)
"""


"""
def detail(request, slug):
    context = {
        'article': get_object_or_404(models.Article.objects.published(), slug=slug)
    }
    return render(request, 'blog/article_detail.html', context)
"""


"""
def category(request, slug, page=1):
    category = get_object_or_404(models.Category.objects.active(), slug=slug,)
    articles_list = models.Article.objects.filter(category=category)
    paginator = Paginator(articles_list, 4)
    articles = paginator.get_page(page)
    context = {
        'category': category,
        'articles': articles
    }
    return render(request, 'blog/category.html', context) 
"""


class ArticleList(ListView):
    queryset = models.Article.objects.published()
    # template_name = 'blog/article_list.html'
    # context_object_name = 'articles'
    paginate_by = 4


class ArticleDetail(DetailView):
    def get_object(self, queryset=None):
        slug = self.kwargs.get('slug')
        return get_object_or_404(models.Article.objects.published(), slug=slug)


class ArticlePreview(ArticleAccessMixin, DetailView):
    def get_object(self, queryset=None):
        pk = self.kwargs.get('pk')
        return get_object_or_404(models.Article, pk=pk)


class CategoryList(ListView):
    paginate_by = 4
    template_name = 'blog/category.html'

    def get_queryset(self):
        global category
        slug = self.kwargs.get('slug')
        category = get_object_or_404(models.Category.objects.active(), slug=slug)
        articles_list = models.Article.objects.filter(category=category)
        return articles_list

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CategoryList, self).get_context_data(**kwargs)
        context['category'] = category
        return context


class AuthorList(ListView):
    paginate_by = 4
    template_name = 'blog/author_list.html'

    def get_queryset(self):
        global author
        username = self.kwargs.get('usr')
        author = get_object_or_404(User, username=username)
        articles = models.Article.objects.filter(author=author)
        return articles

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(AuthorList, self).get_context_data(**kwargs)
        context['author'] = author
        return context

templates/blog/article_detail.html
{% extends 'blog/base.html' %}
{% block title %}{{object.title}}{% endblock %}
{% block main %}

<!-- Page Header -->
<header class="masthead" style="background-image: url('{{object.thumbnail.url}}')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>{{object.title}}</h1>
        </div>
      </div>
    </div>
  </div>
</header>

<article>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto text-justify">
        {% if object.is_special %}
          {% if user.is_authenticated and user.is_special_user or user == object.author or user.is_superuser %}
            {{object.description|safe}}
          {% else %}
            <p>این مقاله ویژه است و برای مشاهده اشتراک تهیه کنید</p>
          {% endif %}
        {% else %}
          {{object.description|safe}}
        {% endif %}
      </div>
    </div>
  </div>
</article>

<hr>


{% endblock %}

templates/blog/article_list.html
{% extends 'blog/list.html' %}


{% block url %}
  {% if page_obj.has_previous %}
    <a href="{% url 'blog:home' page_obj.previous_page_number %}" class="btn btn-primary float-right ml-3">مطالب جدید &rarr;</a>
  {% endif %}
  {% if page_obj.has_next %}
    <a href="{% url 'blog:home' page_obj.next_page_number %}" class="btn btn-primary float-right">مطالب قدیمی &larr;</a>
  {% endif %}
{% endblock %}

templates/blog/author_list.html
{% extends 'blog/list.html' %}

{% block header %}
<h3 class="alert alert-primary text-center">دسته بندی : {{author.get_full_name}}</h3>
{% endblock %}

{% block url %}
{% if page_obj.has_previous %}
<a href="{% url 'blog:author' author.username page_obj.previous_page_number %}" class="btn btn-primary float-right ml-3">مطالب جدید &rarr;</a>
{% endif %}
{% if page_obj.has_next %}
<a href="{% url 'blog:author' author.username page_obj.next_page_number %}" class="btn btn-primary float-right">مطالب قدیمی &larr;</a>
{% endif %}
{% endblock %}

templates/blog/base.html
{% load static %}
{% load base_tags %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'blog/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'blog/css/rtl.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'blog/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="{% static 'blog/css/clean-blog.min.css' %}" rel="stylesheet">

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand" href="{% url 'blog:home' %}">{% title %}</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        {% category_navbar %}
    </div>
</nav>

<!-- Main Content -->

{% block main %}{% endblock %}

<!-- Footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                </ul>
                <p class="copyright text-muted">Copyright &copy; Your Website 2020</p>
            </div>
        </div>
    </div>
</footer>

<!-- Bootstrap core JavaScript -->
<script src="{% static 'blog/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'blog/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Custom scripts for this template -->
<script src="{% static 'blog/js/clean-blog.min.js' %}"></script>

</body>

</html>

templates/blog/category.html
{% extends 'blog/list.html' %}

{% block header %}
    <h3 class="alert alert-primary text-center">دسته بندی : {{category.title}}</h3>
{% endblock %}

{% block url %}
    {% if page_obj.has_previous %}
        <a href="{% url 'blog:category' category.slug page_obj.previous_page_number %}" class="btn btn-primary float-right ml-3">مطالب جدید &rarr;</a>
    {% endif %}
    {% if page_obj.has_next %}
        <a href="{% url 'blog:category' category.slug page_obj.next_page_number %}" class="btn btn-primary float-right">مطالب قدیمی &larr;</a>
    {% endif %}
{% endblock %}

templates/blog/list.html
{% extends 'blog/base.html' %}
{% load static %}
{% block title %}Clean Blog - Start Bootstrap Theme{% endblock %}
{% block main %}

<!-- Page Header -->
<header class="masthead" style="background-image: url('{% static 'blog/img/home-bg.jpg' %}')">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h1>Clean Blog</h1>
                    <span class="subheading">A Blog Theme by Start Bootstrap</span>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            {% block header %}{% endblock %}
            {% for article in object_list %}
            <div class="post-preview">
                <a href="{% url 'blog:detail' article.slug %}">
                    <h2 class="post-title">
                        {{article.title}}
                        {% if article.is_special == True %}
                            <span style="font-size: 14px;" class="badge badge-danger">ویژه</span>
                        {% endif %}
                    </h2>
                    <h3 class="post-subtitle">
                        {{article.description|striptags|truncatewords:10}}
                    </h3>
                </a>
                <p class="post-meta">نوشته شده توسط
                    <a href="{% url 'blog:author' article.author.username %}">{{author.get_full_name}}</a>
                    {{article.jpublish}}</p>
                <div>
                    {% for cat in article.category.active %}
                    <a href="{% url 'blog:category' cat.slug %}">#{{cat.title}}</a>
                    {% endfor %}
                </div>
            </div>
            <hr>
            {% endfor %}
            <div class="clearfix pager-button">
                {% block url %}{% endblock %}
            </div>
        </div>
    </div>
</div>

<hr>

{% endblock %}